disabled_rules:
- trailing_whitespace
- vertical_parameter_alignment

excluded:
- Carthage
- Pods

type_name:
  max_length: 
    warning: 60
    error: 65
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 4
    error: 6
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 600
    error: 1000
    ignore_comment_only_lines: true
identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 
    warning: 90
    error: 200
cyclomatic_complexity:
  ignores_case_statements: true
nesting:
    type_level: 3
reporter: "xcode"